{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ktb-board-express.fullname" . }}-metrics
  labels:
    {{- include "ktb-board-express.labels" . | nindent 4 }}
    monitoring.ktb-board/component: express
spec:
  type: ClusterIP
  selector:
    {{- include "ktb-board-express.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.container.metricsPortName | quote }}
      protocol: TCP
      port: {{ .Values.container.metricsPort }}
      targetPort: {{ .Values.container.metricsPortName | quote }}
{{- end }}
