apiVersion: v1
kind: Service

metadata:
  name: {{ include "ktb-board-express.serviceName" . | quote }}

  labels:
    {{- include "ktb-board-express.labels" . | nindent 4 }}
    monitoring.ktb-board/component: express

  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  type: {{ .Values.service.type }}

  selector:
    {{- include "ktb-board-express.selectorLabels" . | nindent 4 }}

  ports:
    - name: {{ .Values.container.portName | quote }}
      protocol: TCP

      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | quote }}

      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}

  {{- if or
        (eq .Values.service.type "NodePort")
        (eq .Values.service.type "LoadBalancer")
  }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
