repository:
  url: https://github.com/jerry7129/KTB_projects.git
  revision: main

destination:
  server: https://kubernetes.default.svc

project:
  name: ktb-board
  description: ktb-board applications and infrastructure

  clusterResourceWhitelist:
    - group: storage.k8s.io
      kind: StorageClass

    - group: gateway.networking.k8s.io
      kind: GatewayClass

  namespaceResourceWhitelist:
    # ktb-board-infra
    - group: gateway.networking.k8s.io
      kind: Gateway

    - group: gateway.networking.k8s.io
      kind: HTTPRoute

    - group: gateway.k8s.aws
      kind: LoadBalancerConfiguration

    # Spring Target Group 설정
    - group: gateway.k8s.aws
      kind: TargetGroupConfiguration

    # Prometheus Operator 모니터링 설정
    - group: monitoring.coreos.com
      kind: ServiceMonitor

    # 애플리케이션 기본 리소스
    - group: ""
      kind: Service

    - group: ""
      kind: ConfigMap

    - group: ""
      kind: ServiceAccount

    - group: apps
      kind: Deployment

    - group: autoscaling
      kind: HorizontalPodAutoscaler

applications:
  - name: ktb-board-infra
    enabled: true
    path: ktb-board-infra
    releaseName: ktb-board-infra
    destinationNamespace: gateway-system

    sync:
      automated: false
      prune: false
      selfHeal: true

  - name: ktb-board-spring
    enabled: true
    path: ktb-board-spring
    releaseName: ktb-board-spring
    destinationNamespace: default

    sync:
      automated: false
      prune: false
      selfHeal: true

  - name: ktb-board-express
    enabled: true
    path: ktb-board-express
    releaseName: ktb-board-express
    destinationNamespace: default

    sync:
      automated: false
      prune: false
      selfHeal: true
