spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ktb_board?serverTimezone=UTC&sslMode=DISABLED&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.orm.jdbc.bind: trace

server:
  port: ${BACKEND_PORT:8290}

file:
  upload-dir: /Users/ktb_ksg/IdeaProjects/KTB_projects/week2/ImageStorage

jwt:
  secret: ${JWT_SECRET}
  access-token-exp-seconds: 300
  refresh-token-exp-seconds: 1209600