spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

logging:
  level:
    root: info
    org.hibernate.SQL: info

server:
  port: ${SERVER_PORT:8080}

file:
  upload-dir: ${FILE_UPLOAD_DIR:/var/lib/ktb-board/uploads}

jwt:
  secret: ${JWT_SECRET}
  access-token-exp-seconds: 300
  refresh-token-exp-seconds: 1209600

management:
  server:
    port: 9090

  endpoints:
    web:
      exposure:
        include: health,prometheus

  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name:ktb-board-spring}